# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to Npmjs

on:
  repository_dispatch:
    types: [commit-change]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.tag_name }}
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org/
      - run: pnpm publish --access public --registry=https://registry.npmjs.org --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
